[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "*", features = ["tokio"] }
anyhow = "*"
interprocess = "*"
crossbeam = "*"
chrono = "0.4.40"
plotters = "0.3.7"
plotters-iced = "0.11"
rand = { version = "0.9.1", features = ["small_rng"] }
