---
name: Code Linting and Auto-Fix

on:
  push:
    branches: [62-set-up-github-actions]

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Important for Super-Linter: Fetch full git history and all branches
          fetch-depth: 0

      - name: Run Super-Linter with Auto-Fix
        uses: super-linter/super-linter@v7.2.1 # x-release-please-version
        env:
          # DONT VALIDATE EVERYTHING so i can test changes
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: true

          # Lint: Languages and Scripts
          VALIDATE_CPP: true            # --> actual C++ code correctness
          VALIDATE_CLANG_FORMAT: true   # --> C++ code formatting according to CLANG
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true

          # Fix: Languages and Scripts
          FIX_CLANG_FORMAT: true

      - name: Commit fixed files
        run: |
          git config --global user.name 'Auto Linter'
          git config --global user.email 'auto-linter@github.com'
          
          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto-fix linting issues"
            git push
          else
            echo "No linting fixes needed"
          fi
